#!/usr/bin/env python3
"""Write requirements_lock.txt from a `pip freeze` dump.

Invoked by `make lock-deps`. The lock exists because MODULE.bazel's pip.parse()
needs a real PEP 508 requirements file; it used to point at pyproject.toml, which
rules_python reads line-by-line as requirement specifiers and therefore choked on
the first line of TOML punctuation.

Development-only tooling is filtered out: it is installed into the image via the
`dev` extra and is never a Bazel target's dependency, so pinning it here would
only create spurious churn in the lock.
"""

import re
import sys

# Formatters, linters, test runners and their private transitive deps.
_DEV_ONLY = re.compile(
    r"^(black|ruff|flake8|yapf|pre-commit|pytest|pycodestyle|pyflakes|mccabe"
    r"|cfgv|identify|nodeenv|virtualenv|distlib|filelock|platformdirs"
    r"|mypy-extensions|pathspec|iniconfig|pluggy|exceptiongroup|tomli)==",
    re.IGNORECASE,
)

_HEADER = """\
# Pinned dependency lock for the Bazel build.
#
# GENERATED by `make lock-deps` -- do not hand-edit. Regenerate whenever the
# dependency list in pyproject.toml changes.
#
# MODULE.bazel's pip.parse() needs a real requirements lock. It used to name
# //:pyproject.toml, which rules_python parses line-by-line as PEP 508 specifiers
# -- so it aborted on the first line of TOML punctuation and no Bazel target could
# ever resolve a wheel. A pyproject is not a lock in any case: every constraint
# there is `>=`, so it pins nothing.
#
# These are the versions the development container actually resolved, so the
# Bazel build and the image agree by construction.
"""

# The IFTTT directives that go INTO the generated lock are assembled from pieces.
# tools/hooks/check_ifttt.py scans every tracked file for directive comments, so a
# literal "LINT.IfChange(...)" sitting in this generator's template would be read
# as a directive on *this* file -- an unpaired one, failing `make check-ifttt`.
_MARK = "# LINT."
_LOCK_IF_CHANGE = f"{_MARK}IfChange(lock)\n"
_LOCK_THEN_CHANGE = f"{_MARK}ThenChange(//pyproject.toml:dependencies)\n"


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(f"usage: {argv[0]} <pip-freeze-file> <output-lock>", file=sys.stderr)
        return 2

    with open(argv[1], encoding="utf-8") as handle:
        pins = [
            line.strip()
            for line in handle
            if line.strip() and "==" in line and not _DEV_ONLY.match(line.strip())
        ]

    if not pins:
        print(f"{argv[0]}: refusing to write an empty lock from {argv[1]}", file=sys.stderr)
        return 1

    with open(argv[2], "w", encoding="utf-8") as handle:
        handle.write(_HEADER)
        handle.write(_LOCK_IF_CHANGE)
        handle.write("\n".join(sorted(pins, key=str.lower)))
        handle.write("\n")
        handle.write(_LOCK_THEN_CHANGE)

    print(f"{argv[2]}: {len(pins)} pinned requirements")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
